100 crear vista de costos de envio frontend
AnderMendoza/Ecommerce-Template pull request #101
Opened 2022-10-30 23:06 UTC by yeshua-aguilar

se ha creado la pagina de costo de envio con informacion para el cliente

![imagen](https://user-images.githubusercontent.com/81573986/198906256-003aa7fa-d279-4c29-93a3-75845776ac76.png)

2022-10-30 23:46 UTC, AnderMendoza commented
Gran aporte @yeshua-aguilar solo te pediría que vincules a todas las demás vistas. Estoy atento a la corrección. 😉👌

2022-11-03 22:50 UTC, yeshua-aguilar commented
ya se ha vinculado en enlace en el index para que se dirija en a la pagina de costo

2022-11-03 23:06 UTC, AnderMendoza requested changes
Te falta enlazar en el header-nav y footer de todas las demás vistas.
Espero tu actualización 😉

2022-11-03 23:14 UTC, yeshua-aguilar commented
si tiene el footer
y la parte cabecera

2022-11-04 03:14 UTC, AnderMendoza approved these changes
Queda pendiente el modo responsive y ajustar el texto

2022-11-04 03:15 UTC, merged